export type FontEntry = { key: string; label: string; style: string };

// All fonts sorted A-Z by key.
// Google Fonts entries require the font to be loaded in globals.css.
// System font entries work without any loading.
export const CANVAS_FONTS: FontEntry[] = [
  { key: "Anton",              label: "Anton",           style: "'Anton', sans-serif" },
  { key: "Arial",              label: "Arial",           style: "Arial, Helvetica, sans-serif" },
  { key: "Baskerville",        label: "Baskerville",     style: "Baskerville, 'Baskerville Old Face', 'Hoefler Text', Georgia, serif" },
  { key: "Bebas Neue",         label: "Bebas Neue",      style: "'Bebas Neue', sans-serif" },
  { key: "Bookman",            label: "Bookman",         style: "'Bookman Old Style', Bookman, 'Book Antiqua', Georgia, serif" },
  { key: "Cabin",              label: "Cabin",           style: "'Cabin', sans-serif" },
  { key: "Calibri",            label: "Calibri",         style: "Calibri, Candara, 'Segoe UI', Optima, sans-serif" },
  { key: "Cambria",            label: "Cambria",         style: "Cambria, Georgia, serif" },
  { key: "Candara",            label: "Candara",         style: "Candara, Calibri, 'Segoe UI', Optima, sans-serif" },
  { key: "Century Gothic",     label: "Century Gothic",  style: "'Century Gothic', CenturyGothic, AppleGothic, sans-serif" },
  { key: "Comic Sans MS",      label: "Comic Sans",      style: "'Comic Sans MS', 'Comic Sans', cursive" },
  { key: "Comfortaa",          label: "Comfortaa",       style: "'Comfortaa', sans-serif" },
  { key: "Consolas",           label: "Consolas",        style: "Consolas, 'Courier New', monospace" },
  { key: "Courier New",        label: "Courier New",     style: "'Courier New', Courier, monospace" },
  { key: "Dancing Script",     label: "Dancing Script",  style: "'Dancing Script', cursive" },
  { key: "Didot",              label: "Didot",           style: "Didot, 'Didot LT STD', 'Hoefler Text', Garamond, 'Times New Roman', serif" },
  { key: "DM Sans",            label: "DM Sans",         style: "'DM Sans', sans-serif" },
  { key: "Fira Code",          label: "Fira Code",       style: "'Fira Code', monospace" },
  { key: "Franklin Gothic",    label: "Franklin Gothic", style: "'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif" },
  { key: "Futura",             label: "Futura",          style: "Futura, 'Century Gothic', CenturyGothic, AppleGothic, sans-serif" },
  { key: "Garamond",           label: "Garamond",        style: "Garamond, 'Hoefler Text', 'Times New Roman', serif" },
  { key: "Georgia",            label: "Georgia",         style: "Georgia, 'Times New Roman', serif" },
  { key: "Gill Sans",          label: "Gill Sans",       style: "'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif" },
  { key: "Great Vibes",        label: "Great Vibes",     style: "'Great Vibes', cursive" },
  { key: "Helvetica",          label: "Helvetica",       style: "Helvetica, Arial, sans-serif" },
  { key: "Impact",             label: "Impact",          style: "Impact, 'Haettenschweiler', 'Arial Narrow Bold', sans-serif" },
  { key: "Inter",              label: "Inter",           style: "'Inter', sans-serif" },
  { key: "JetBrains Mono",     label: "JetBrains Mono", style: "'JetBrains Mono', monospace" },
  { key: "Josefin Sans",       label: "Josefin Sans",   style: "'Josefin Sans', sans-serif" },
  { key: "Lato",               label: "Lato",            style: "'Lato', sans-serif" },
  { key: "Lucida Console",     label: "Lucida Console",  style: "'Lucida Console', Monaco, monospace" },
  { key: "Monaco",             label: "Monaco",          style: "Monaco, 'Lucida Console', monospace" },
  { key: "Montserrat",         label: "Montserrat",      style: "'Montserrat', sans-serif" },
  { key: "Mulish",             label: "Mulish",          style: "'Mulish', sans-serif" },
  { key: "Nunito",             label: "Nunito",          style: "'Nunito', sans-serif" },
  { key: "Open Sans",          label: "Open Sans",       style: "'Open Sans', sans-serif" },
  { key: "Optima",             label: "Optima",          style: "Optima, Segoe, 'Segoe UI', Candara, Calibri, Arial, sans-serif" },
  { key: "Oswald",             label: "Oswald",          style: "'Oswald', sans-serif" },
  { key: "Pacifico",           label: "Pacifico",        style: "'Pacifico', cursive" },
  { key: "Palatino",           label: "Palatino",        style: "Palatino, 'Palatino Linotype', 'Book Antiqua', Georgia, serif" },
  { key: "Playfair Display",   label: "Playfair Display",style: "'Playfair Display', serif" },
  { key: "Poppins",            label: "Poppins",         style: "'Poppins', sans-serif" },
  { key: "Quicksand",          label: "Quicksand",       style: "'Quicksand', sans-serif" },
  { key: "Raleway",            label: "Raleway",         style: "'Raleway', sans-serif" },
  { key: "Roboto",             label: "Roboto",          style: "'Roboto', sans-serif" },
  { key: "Segoe UI",           label: "Segoe UI",        style: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif" },
  { key: "Space Mono",         label: "Space Mono",      style: "'Space Mono', monospace" },
  { key: "Syne",               label: "Syne",            style: "'Syne', sans-serif" },
  { key: "Tahoma",             label: "Tahoma",          style: "Tahoma, Geneva, sans-serif" },
  { key: "Times New Roman",    label: "Times New Roman", style: "'Times New Roman', Times, serif" },
  { key: "Trebuchet MS",       label: "Trebuchet MS",    style: "'Trebuchet MS', Helvetica, sans-serif" },
  { key: "Ubuntu",             label: "Ubuntu",          style: "'Ubuntu', sans-serif" },
  { key: "Verdana",            label: "Verdana",         style: "Verdana, Geneva, sans-serif" },
];

export function getFontStyle(font: string | undefined, fallback = "'DM Sans', sans-serif"): string {
  if (!font) return fallback;
  return CANVAS_FONTS.find(f => f.key === font)?.style ?? `'${font}', sans-serif`;
}
